### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by Adiost** [ahfuck/AP_Errata#9]
This needs to explain what this repo is and what it offers in a single sentence

![image](https://user-images.githubusercontent.com/7739280/120937664-65248700-c717-11eb-9662-2f0f6cc5effb.png)

**Comment by sannennetarou** [comment]
I'll add a description today, and maybe rename the project sometime down
the line.

To be honest the reason I haven't written a description yet is because I
wasn't sure how many steps between exporting and importing we'll cover.
